travelclick_bookingmask.ihotelier:
  type: config_object
  label: 'TravelClick iHotelier Endpoint URL'
  mapping:
    hotelid:
      type: number
      label: 'Hotel ID'
    endpointurl:
      type: url
      label: 'Endpoint URL'